# 站點基本資訊
title: J個嚇嚇
description: J個嚇嚇和蟹堡珊瑚的小天地


# 方式一：使用 GitHub Pages 內建支援的主題之一（擇一）
theme: jekyll-theme-minimal # 也可改成 jekyll-theme-cayman / merlot / slate... 等


# 方式二：remote_theme（能用 pages-themes 的新版樣式）
# 使用 remote_theme 時，建議同時啟用對應外掛
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
